### ISSUE TITLE
"Trainings" Tab cannot be opened

### ISSUE THREAD

**Issue by ghost** [oliexdev/openWorkout#46]
**Describe the bug**
When clicking the Tab "Training" in the menu, the app shows me that "an unexpected error occured. Sorry for the inconvenience". I hope I will get back my saved trainings, as it was a lot of work to create them. I downloaded the app some days ago and create all the workouts on the first day. It was working on the first day, but after somedays when I opened the app again, it is not possible to go to the saved trainings. Restarting/closing the app does not solve the error. It is also not possible to start a workout in "Trainings".

**To Reproduce**
1. Go to "training", but not everybody will experience it.

**Expected behavior**
"My exercises should be shown.

**Debug log**
Build version: 1.3.1
Build date: 1981-01-01 01:01:02
Current date: 2021-04-15 09:56:51
Device: OnePlus ONE A2001

Stack trace:
java.lang.IllegalArgumentException: Self-causation not permitted
at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1420)
at android.graphics.ImageDecoder$ContentResolverSource.createImageDecoder(ImageDecoder.java:277)
at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1743)
at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1736)
at android.widget.ImageView.getDrawableFromUri(ImageView.java:1011)
at android.widget.ImageView.resolveUri(ImageView.java:980)
at android.widget.ImageView.setImageURI(ImageView.java:557)
at androidx.appcompat.widget.o.setImageURI(Unknown Source:0)
at com.health.openworkout.gui.training.d.Y(Unknown Source:37)
at com.health.openworkout.gui.training.d.u(Unknown Source:2)
at androidx.recyclerview.widget.RecyclerView$g.v(Unknown Source:0)
at androidx.recyclerview.widget.RecyclerView$g.d(Unknown Source:29)
at androidx.recyclerview.widget.RecyclerView$v.H(Unknown Source:39)
at androidx.recyclerview.widget.RecyclerView$v.I(Unknown Source:498)
at androidx.recyclerview.widget.RecyclerView$v.p(Unknown Source:5)
at androidx.recyclerview.widget.RecyclerView$v.o(Unknown Source:1)
at androidx.recyclerview.widget.LinearLayoutManager$c.d(Unknown Source:11)
at androidx.recyclerview.widget.LinearLayoutManager.t2(Unknown Source:0)
at androidx.recyclerview.widget.LinearLayoutManager.V1(Unknown Source:38)
at androidx.recyclerview.widget.LinearLayoutManager.Y0(Unknown Source:356)
at androidx.recyclerview.widget.RecyclerView.E(Unknown Source:38)
at androidx.recyclerview.widget.RecyclerView.C(Unknown Source:37)
at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:70)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at androidx.constraintlayout.widget.ConstraintLayout.onLayout(Unknown Source:70)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at com.google.android.material.appbar.b.F(Unknown Source:135)
at com.google.android.material.appbar.c.l(Unknown Source:0)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:42)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
at android.view.View.layout(View.java:22466)
at android.view.ViewGroup.layout(ViewGroup.java:6304)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3157)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2614)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
at android.view.Choreographer.doCallbacks(Choreographer.java:791)
at android.view.Choreographer.doFrame(Choreographer.java:726)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

**Comment by oliexdev** [comment]
Did you delete some images or moved some files around?
